apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: morningfragrance-com-tls
spec:
  secretName: morningfragrance-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: morningfragrance.com
  dnsNames:
    - morningfragrance.com
    - www.morningfragrance.com