apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: morning-fragrance-com-tls
spec:
  secretName: morning-fragrance-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: morningfragrance.com
  dnsNames:
    - morningfragrance.com
    - www.morningfragrance.com